---
- hosts: all
  gather_facts: no

  tasks:
  - name: Actualización de VM tools
    vmware_guest_tools_upgrade:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      name: "{{ vm_name }}"
    delegate_to: localhost
