---
- name: Resume PRTG sensors of a host
  hosts: all
  connection: local
  gather_facts: no

  vars:
    token_prtg: "{{ lookup('env', 'PRTG_TOKEN') }}"

  tasks:
    - name: Optener DNS info de la VM
      vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        folder: "/{{ datacenter_name }}/"
        name: "{{ inventory_hostname }}"
        schema: vsphere
        properties:
          - guest.ipStack
      delegate_to: localhost
      register: vm_info

    - name: Guardar variable hostname
      set_fact:
        hostName: "{{ vm_info.instance.guest.ipStack.0.dnsConfig.hostName }}"

    - name: Get objectID of the host
      uri:
        url: https://acaprtg01d.asociacioncibao.com.do/api/table.json?content=devices&columns=objid&filter_name={{ hostName }}&apitoken={{ token_prtg }}
        return_content: yes
        validate_certs: no
      delegate_to: localhost
      no_log: true
      register: prtg_sensors

    - debug:
        msg: "objectID del Sensor: {{ prtg_sensors.json.devices[0].objid }}"

    - name: Resume PRTG sensors of the host
      uri:
        url: https://acaprtg01d.asociacioncibao.com.do/api/pauseobjectfor.htm?id={{ prtg_sensors.json.devices[0].objid }}&action=1&pausemsg=Resumido_por_Ansible&apitoken={{ token_prtg }}
        return_content: yes
        validate_certs: no
      delegate_to: localhost
      no_log: true
      when: prtg_sensors.json.devices[0].objid is defined
