---
- name: Info de VM
  hosts: all
 
  tasks:
    - name: Optener info de la VM
      vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        folder: "/{{ datacenter_name }}/"
        name: "{{ inventory_hostname }}"   
        schema: vsphere
        properties:
          - guest.ipStack
      delegate_to: localhost
      register: vm_info
